package com.cgutech.meeting.entity;
// Generated 2016-10-20 16:27:58 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * MeetingMinutes generated by hbm2java
 */
@Entity
@Table(name = "meeting_minutes", catalog = "cgu_meeting_system")
public class MeetingMinutes implements java.io.Serializable {

	private Integer id;
	private String title;
	private String author;
	private String content;
	private String ctime;

	public MeetingMinutes() {
	}

	public MeetingMinutes(String title, String author, String content,String ctime) {
		this.title = title;
		this.author = author;
		this.content = content;
		this.ctime = ctime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", nullable = false, length = 12)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "content", nullable = false, length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "ctime", nullable = false, length = 19)
	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

}
