package com.cgutech.meeting.entity;
// Generated 2016-10-20 16:27:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "cgu_meeting_system")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String role;
	private String pswd;
	private String roleUuid;
	private String ctime;

	public User() {
	}

	public User(String uname, String role, String pswd, String roleUuid) {
		this.name = uname;
		this.role = role;
		this.pswd = pswd;
		this.roleUuid = roleUuid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uname", nullable = false, length = 12)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", nullable = false, length = 5)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "pswd", nullable = false)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@Column(name = "role_uuid", nullable = false, length = 8)
	public String getRoleUuid() {
		return this.roleUuid;
	}

	public void setRoleUuid(String roleUuid) {
		this.roleUuid = roleUuid;
	}

	public String getCtime() {
		return ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

}
